services:
  xcell-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DITTO_APP_ID: ${DITTO_APP_ID}
        DITTO_PLAYGROUND_TOKEN: ${DITTO_PLAYGROUND_TOKEN}
        DITTO_AUTH_URL: ${DITTO_AUTH_URL}
        DITTO_WEBSOCKET_URL: ${DITTO_WEBSOCKET_URL}
    ports:
      - "8080:80"
    restart: unless-stopped
